jobs:
  include:
    - stage: build
      sudo: required
      services:
        - docker
      env:
        DOCKER_COMPOSE_VERSION: 1.27.4
       cache:
        directories:
          - /home/Trabalho-Individual-2020-1/api/node_modules
          - /home/Trabalho-Individual-2020-1/client/node_modules
      before_install:
        - sudo rm /usr/local/bin/docker-compose
        - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
        - chmod +x docker-compose
        - sudo mv docker-compose /usr/local/bin
      before_script:
        - docker-compose up -d --build
      script:
        - docker-compose run api rake db:create 
        - docker-compose run api rake db:migrate
      after_script:
        - docker-compose down
    - stage: test-api
      script:
        - docker-compose run api rake db:create 
        - docker-compose run api rake db:migrate
        - docker-compose run api bundle exec rails test
    - stage: test-client
      script:
        - docker-compose run client yarn run test:unit
